name: Docker build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
          cache-dependency-path: |
            .github/actions/get-dockerhub-version-tag/go.sum
            .github/actions/get-pecl-package-version/go.sum
      - run: .github/scripts/check.sh
