name: Docker publish

on:
  push:
    branches:
      - main

    tags:
      - wp*

env:
  IMAGE_NAME: wordpress-xdebug

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker build . --file Dockerfile

  tag:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Get dockerhub wordpress latest version tag
        id: image-tag
        uses: ./.github/actions/get-dockerhub-version-tag
        with:
          org: 'library'
          repo: 'wordpress'

      - name: Get Xdebug pecl package version
        id: package-version
        uses: ./.github/actions/get-pecl-package-version
        with:
          package: 'xdebug'
          stability: 'stable'

      - name: Create tag
        id: create-tag
        run: echo "::set-output name=tag::wp${{ steps.image-tag.outputs.tag}}-xdebug${{ steps.package-version.outputs.version }}"

      - name: Push tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.create-tag.outputs.tag }}",
              sha: context.sha
            })

  push:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Version from created tag
          VERSION=${{ needs.tag.outputs.tag }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
